name: Generate MistyOS ISO
on:
  workflow_dispatch:
jobs:
  build-iso:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: read
    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build ISO
        uses: ublue-os/titanoboa@main
        id: build
        with:
          image-ref: ghcr.io/officialqivon/mistyos:latest
          hook-post-rootfs: ${{ github.workspace }}/installer/configure-iso.sh
          compression: squashfs

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MistyOS-ISO
          path: /home/runner/work/_actions/ublue-os/titanoboa/main/output.iso

      - name: Split and Upload Release
        run: |
          gh release create v1.0.${{ github.run_number }} \
            --title "MistyOS Build ${{ github.run_number }}" \
            --notes "Download all parts and run 'cat MistyOS.iso.part* > MistyOS.iso' to combine." \
            --repo ${{ github.repository }} || echo "Exists"
          split -b 2000M /home/runner/work/_actions/ublue-os/titanoboa/main/output.iso MistyOS.iso.part
          gh release upload v1.0.${{ github.run_number }} MistyOS.iso.part* \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
